### PR TITLE
Updated TinyMCE assets to version 3.4

### PR DESCRIPTION
**Pull request by sgerrand**
Hi,

I've updated the TinyMCE assets as per your request and requirements at https://github.com/kete/tiny_mce/blob/master/DEV_UPGRADE_NOTES.rdoc

Note that new language translations have been added. 

As a side note, it'd be good at a future point to change the type of TinyMCE that is used (Prototype/jQuery) based on a configuration directive.

-Sasha

### CODE REVIEW

**Comment by walter** [comment]
How about running the tests? Did they all pass in Rails 3.x and/or Rails 2.3?

**Comment by sgerrand** [comment]
No. However, they didn't pass previously in either Rails version 2.3 or 3 for the version that I forked from.

**Comment by walter** [comment]
I take that to mean that the tests that were failing before are still failing and there are no new failures or other differences when running the tests.

Correct?

**Comment by sgerrand** [comment]
That's right. I wasn't meaning to be obtuse, so apologies if my comment was interpreted as such.

I'll work on fixing the tests over the weekend. Would you prefer that the fixes were added to this pull request?

**Comment by walter** [comment]
No problem, I just wanted to make sure I was clear.

A separate pull request for the test fixes makes sense to me. I'm sorry there was test rot. I took over as maintainer and discovered things weren't quite in order only after accepting a pull request that made the problem worse. Haven't had time to do much to get things in order. So I appreciate you working on it.

Cheers,
Walter

**Comment by walter** [comment]
Hey @sgerrand,

Any progress on getting the 3.4 based TinyMCE gem's tests working?

Cheers,
Walter

**Comment by sgerrand** [comment]
Hi @walter,

Sorry for this tardy response. I was caught up with a bunch of work projects during April and didn't get to complete the patches for the failing unit tests. I'll have time later this week to do so, so should have them committed by the weekend.

-Sasha

**Comment by walter** [comment]
I know how it goes. Looking forward to getting rid of the test rot. Thanks in advance.

**Pull request merged**
